### ISSUE TITLE
Series added by AutoOrganize result in duplicate

### ISSUE THREAD

**Issue by jankete** [MediaBrowser/Emby.AutoOrganize#8]
When a series is added by AutoOrganize for the first time (means: the show didn't exist before), it shows up two times in series dropdown afterwards.

![11-04-_2018_07-36-25](https://user-images.githubusercontent.com/22338766/38598874-7adf039a-3d5e-11e8-8f10-2b68ee338f70.png)

**Comment by PoppyPop** [comment]
Hello,

Commit afb91056 should fix this bug.

**Comment by PoppyPop** [comment]
Could you check with the latest release if the problem still occur ?

**Comment by jankete** [comment]
Today I updated the plugin to the latest version. The next days I'll check, if the duplicates are still present.

**Comment by jankete** [comment]
Now I added a new series an it was only added once. So the error seems to be fixed. But the previous addesdduplicates (from my screenshot) are still present in the dropdown. How can I get rid of them?

**Comment by PoppyPop** [comment]
As stated in #10 PR by luke this is probably a core issue existing before i made update to the plugin (it's an untouched logic). I will remove my fix in a futur release.

I will look to open a proper issue for the emby core.

**Comment by ghost** [comment]
I have just installed new Emby server and this issue is still happening.

**Comment by LukePulverenti** [comment]
This is resolved for the next release of Emby Server. Resolved in the sense that it will not happen anymore, however it will not correct any pre-existing duplicates. Once the next release is available, you can always do a fresh install or delete your library database if you are willing to do that. thanks.
